apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
logging:
  level:
    default: info
provider:
  type: Kubernetes
  kubernetes:
    rateLimitDeployment:
      container:envoyproxy/envoy:distroless-v1.30-latest
extensionApis:
  enableEnvoyPatchPolicy: true
