apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: sykoramarek/ambulance-ufe
  newName: sykoramarek/ambulance-ufe
  newTag: 1.0.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: sykoramarek/ambulance-wl-webapi
  newName: sykoramarek/ambulance-wl-webapi
  newTag: 1.0.1

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: msy-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  msy-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1